spring:
  application:
    name: ThermalBack
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/dbforthermal
    username: art
    password: art
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/dbforthermal
    user: art
    password: art
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1.0.0
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

cert:
  path:
    privateKey: src/main/resources/cert.dev/ec_private_key.pem
    publicKey: src/main/resources/cert.dev/ec_public.pem

server:
  port: 7070

jwt:
  jwt-expired-time: 1
  jwt-refresh-expired-time: 120

sms:
  service:
    login: RosEcology
    password: R302511r%

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operations-sorter: alpha
    tags-sorter: alpha